### ISSUE TITLE
Why does mailparser not emit errors?

### ISSUE THREAD

**Issue by jamhall** [andris9/mailparser#105]
Hi!

Is there a reason mailparser does not emit errors?

Let's say I try to parse an invalid eml file, unfortunately I won't get any errors. Any way around this?

Cheers!

Great module by the way.

**Comment by andris9** [comment]
Mailparser is a forgiving parser as a lot (if not most of) the e-mail messages are invalid. Some use too long lines, some fail to define the correct charset, some set unicode attachment filenames invalidly etc. So being strict only makes sense if you're building a format validator which mailparser is not.
