### ISSUE TITLE
When parsing email headers "date" header takes priority over "received" and "x-received" headers

### ISSUE THREAD

**Issue by AVVS** [andris9/mailparser#108]
This is nasty when message was sent few hours prior to delivery

Email sent: `"date": "Thu, 5 Feb 2015 21:20:19 -0800"`
Delivered: `Fri, 6 Feb 2015 08:07:56 -0800`

Example parsed headers. Emails had been changed and not relevant pieces removed:

```json
               "headers": {
                  "delivered-to": "email@example.com",
                  "received": [
                     "by 10.182.131.37 with SMTP id oj5csp1865624obb; Fri, 6 Feb 2015 08:07:56 -0800 (PST)",
                     "from mail-wg0-x23a.google.com (mail-wg0-x23a.google.com. [2a00:1450:400c:c00::23a]) by mx.google.com with ESMTPS id qk9si5164288wjc.22.2015.02.06.08.07.36 for <email@example.com> (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128); Fri, 06 Feb 2015 08:07:38 -0800 (PST)",
                     "by mail-wg0-f58.google.com with SMTP id z12sf2041991wgg.3 for <email@example.com>; Fri, 06 Feb 2015 08:07:35 -0800 (PST)",
                     "by 10.152.25.201 with SMTP id e9ls258866lag.67.gmail; Fri, 06 Feb 2015 08:07:32 -0800 (PST)",
                     "by 10.194.240.36 with SMTP id vx4mswjc; Thu, 5 Feb 2015 21:20:40 -0800 (PST)",
                     "from mail-lb0-x235.google.com (mail-lb0-x235.google.com. [2a00:1450:4010:c04::235]) by gmr-mx.google.com with ESMTPS id mv2si127556lbc.0.2015.02.05.21.20.40 for <example@googlegroups.com> (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128); Thu, 05 Feb 2015 21:20:40 -0800 (PST)",
                     "by mail-lb0-x235.google.com with SMTP id u14so8591658lbd.12 for <example@googlegroups.com>; Thu, 05 Feb 2015 21:20:40 -0800 (PST)",
                     "by 10.112.184.133 with HTTP; Thu, 5 Feb 2015 21:20:19 -0800 (PST)"
                  ],
                  "x-received": [
                     "by 10.194.193.99 with SMTP id hn3mr9339066wjc.148.1423238858397; Fri, 06 Feb 2015 08:07:38 -0800 (PST)",
                     "by 10.152.171.103 with SMTP id at7mr37408lac.19.1423238855864; Fri, 06 Feb 2015 08:07:35 -0800 (PST)",
                     "by 10.112.161.201 with SMTP id xu9mr575841lbb.11.1423238852236; Fri, 06 Feb 2015 08:07:32 -0800 (PST)",
                     "by 10.180.88.66 with SMTP id be2mr59934wib.1.1423200040208; Thu, 05 Feb 2015 21:20:40 -0800 (PST)",
                     "by 10.112.26.110 with SMTP id k14mr1097350lbg.29.1423200040062; Thu, 05 Feb 2015 21:20:40 -0800 (PST)"
                  ],
                  "date": "Thu, 5 Feb 2015 21:20:19 -0800"
               },
```

**Comment by andris9** [comment]
I don't really see what is the issue here, could you elaborate what do you expect instead of the current behavior?

**Comment by AVVS** [comment]
@andris9 The use-case here is the following:

1. User A sends an email to a group-list at 9 pm 4th of february. This is what the "date" header would reflect.
2. Some time passes by, message is wondering around inside queues and finally gets to the recipient on 5th of february 11am

This message's delivery time differs greatly from when it was originally sent. Therefore one must use the delivery date and not the date when the message was originally sent. Furthermore, this is exactly what gmail does when displaying conversations - it sorts messages by the date from the received and x-received headers granted that they are present.

I've added the PR that implements the desired behavior

**Comment by AVVS** [comment]
Another idea is that If you really want to make this backwards compatible - you can add `.receivedDate` property along with the `date`, but I cant really think of any real use-case for this. IE, messages that were sent by the user will naturally lack `received` headers, and messages received by another user should be dated using received date

**Comment by andris9** [comment]
Thats not exactly how the dates in email work. Firstly the `received` is known to be used loosely by transmitting servers which means that even though in theory the value can be tokenized it should be treated as human readable text. `x-received` is not even a standard so we cant really assume anything about the formatting.

For example here's a `received` header from a random email in my inbox:

    Received: from mx1006.sendsmaily.info (149.154.156.6) by
       mx1008.sendsmaily.info id hk0p9a19s3go for <andris.reinman@gmail.com>;
       Tue, 17 Jun 2014 15:18:56 +0300 (envelope-from <bounce@mx1008.sendsmaily.info>)

Trying to parse the date out of this fails as there's a string value where timezone name is expected.

How the dates are actually handled is that in addition to the message itself, the receiving server stores some metadata about the message, which includes the `internaldate` value – this is the time that the message was received by the server.

Here's an example IMAP query against Gmail IMAP where I ask for the internaldate value and date header value (date is included in the envelope property)

```
tag1 fetch 49 (internaldate envelope)
* 49 FETCH (INTERNALDATE "09-Feb-2015 00:51:32 +0000" ENVELOPE ("Mon, 09 Feb 2015 00:51:30 +0000" ...)
tag1 OK Success
```

As you can see the values are slightly different (only for few seconds but still these are different values), header date shows when the message was sent (or actually, when it was claimed to be sent as we can't verify it) and internaldate shows when the message was received. When GMail displays you the message you see the internaldate value but if you ask for the date value in IMAP (either by `ENVELOPE` or `BODY[HEADER.FIELDS (DATE)]`), you always get the value form the `Date` header.

Anyway I would not change the current `date` handling as the `date` property should include the `Date` header value but adding a separate informational `received` property that includes the date from either the first `received` or `x-received` header would make sense. So if  you'd change the PR to not mix these values with actual `date` I'd pull it.

**Comment by AVVS** [comment]
@andris9 updated PR, now it parses `received` and `x-received` headers into `receivedDate` property
