### ISSUE TITLE
Node.js error: Assertion failed: (start <= end), function SliceOnto, file ../src/smalloc.cc, line 281

### ISSUE THREAD

**Issue by breck7** [andris9/mailparser#113]
When iterating over a large mbox file, passing each message into mailparser, my node process crashes consistently with the error:

"Assertion failed: (start <= end), function SliceOnto, file ../src/smalloc.cc, line 281. Abort trap: 6"

It may be related to this bug: https://github.com/joyent/node/issues/9180

It happens on certain messages consistently but ONLY after a few thousands messages have been parsed. In other words, if I go directly to the problem messages parsing works fine. But if they are processed in a loop a few thousand iterations in I get the crash.

I'm investigating further but wanted to file this in case other people are seeing it.

Node version v0.12.0

Output:
"node app.js email.mbox
File size: 9737455534
processing message 1000...
processing message 2000...
processing message 3000...
Assertion failed: (start <= end), function SliceOnto, file ../src/smalloc.cc, line 281.
Abort trap: 6"

**Comment by breck7** [comment]
I used "n" to switch to v0.11.9 and my app worked fine. My guess is the fix for 9180 in the upcoming 0.12.1 will solve this for 12.

**Comment by andris9** [comment]
Yes, seems like an issue with node itself
