### ISSUE TITLE
Getting mailparser works in borwser

### ISSUE THREAD

**Issue by lygstate** [andris9/mailparser#129]
Or distribute it with bower

**Comment by andris9** [comment]
See http://emailjs.org/ for stuff that works in browser.

**Comment by nutphi** [comment]
I'm not sure if the library's already obsolete or not and the one I want to use ([emailjs-mime-parser](https://github.com/emailjs/emailjs-mime-parser)).
It said 'Felix is not actively maintaining this library anymore' and last update was 6 months ago.
I would like to make sure if it is still good to use the lib or not.
