### ISSUE TITLE
Pass Variables Into "end"

### ISSUE THREAD

**Issue by BradRuderman** [andris9/mailparser#134]
What is the best strategy for passing variables into the "end" event? For example if I wanted to pass a file name? I have tried wrapping the end into a function and then passing a variable into the function however its inefficient for memory to create all those binders:

function processEmail(fileName){

mailparser.on("end", function(mailObject){
});
var body = 'EMAIL - CONTENTS FROM FILE';
mailparser.write(body);
mailparser.end();
}
var fileName = 'FILENAME';
processEmail(fileName);

**Comment by andris9** [comment]
You need to generate a separate parser for every message, so you could do something like this: ```javascript
var mailparser = new MailParser();
mailparser.fileName = fileName;
...
mailparser.on('end', function(){
     console.log(mailparser.fileName);
});
```
