### ISSUE TITLE
mime test set

### ISSUE THREAD

**Issue by seriousme** [andris9/mailparser#135]
Hi,

I noticed that your testset is rather small. 
A bigger testset of mime messages can be found at: https://github.com/Mailgarant/mime-test-cases

Kind regards,
Hans

**Comment by andris9** [comment]
It seems to me that these test cases are more meant for mail clients to properly display messages (eg. handling winmail.dat, choosing between html/text etc.) which are not so important in the context of mailparser. There doesn't seem to be anything too complex or weird in these test cases that needs to be cehcked against. Mailparser tests against smaller details, for example handling format=flowed like [this](https://github.com/andris9/mailparser/blob/master/test/mailparser.js#L805-L815).

**Comment by seriousme** [comment]
My apologies. I overlooked the small tests in https://github.com/andris9/mailparser/blob/master/test/mailparser.js
and only saw the one nested.eml ;-)

Kind regards,
Hans
