### ISSUE TITLE
Support for TNEF

### ISSUE THREAD

**Issue by ricardopolo** [andris9/mailparser#145]
Hi. 

We use mailparser in our solutions, our solutions integrates with Office 365 and Exchange, and they both have [TNEF](https://en.wikipedia.org/wiki/Transport_Neutral_Encapsulation_Format) enabled by default . This is a Microsoft specific standard for mail messages and they used to send emails using this format when sending emails outside the organization. It basically encapsulates the whole email inside an attachment caled `winmail.dat`

We found mailparser does not support TNEF, so we cannot parse emails sent in these format. And sadly there are a lot of emails in these format.  Are there any reason for not supporting it?

There are libraries out there that support it like MimeKit https://github.com/jstedfast/MimeKit. 

In the future we could expect this Mail Parser supporting this emails?

**Comment by ricardopolo** [comment]
Any comment @andris9? Thanks :)

**Comment by andris9** [comment]
Sorry, didn't notice this issue before.

TNEF is Microsoft's proprietary format. Some data can be parsed out of it but not all and thus there's not much support for TNEF outside the Microsoft-world. MimeKit is written in .net which is also part of Microsoft-world and thus has access to proper TNEF handling.

Anyway, for now I have no plans for adding support for it. If there would be a cross-platform and reliable TNEF parser written in javaScript then I probably would add it but I don't know any such parsers.
