### ISSUE TITLE
Error after merging pull request #148

### ISSUE THREAD

**Issue by Sjonnie2nd** [andris9/mailparser#150]
On parsing one of my emails node crashes on mailParser.js line 1047:
`} else if (this.mailData.text[i].content) {`.
The error message: Cannot read property 'content' of undefined.
This seems to be caused by #148 

When debugging: 
i=1, 
this.mailData.html.length=2
this.mailData.text.length=1.

Without digging too much in the surrounding code i fixed this with:
`} else if (i < this.mailData.text.length && this.mailData.text[i].content) {`

Am I right here?

**Comment by andris9** [comment]
Fix published as v0.6.1
