### ISSUE TITLE
Duplicate mail object or Multiple "end" events fired?

### ISSUE THREAD

**Issue by omarusman** [andris9/mailparser#156]
Hi everyone,

Just want to raise an issue I'm encountering. 

It seems the "end" event is fired multiple times, thus instantiating multiple (duplicate) mail object.
I'm not sure about this, though. Do you have any idea of a fix?

Screencast: https://vid.me/hICa

Thank you in advance.

**Comment by andris9** [comment]
Create a new mailparser instance for every message you want to parse
