### ISSUE TITLE
Refusing to Install

### ISSUE THREAD

**Issue by darren-white72** [andris9/mailparser#157]
Hello,

I am having trouble installing this module as it is refusing to install mailparser as a dependency of itself.

Here is the debug log

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'mailparser',
1 verbose cli   '--save' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData mailparser
8 silly fetchNamedPackageData mailparser
9 silly mapToRegistry name mailparser
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'mailparser',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'mailparser',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/mailparser
14 verbose request uri https://registry.npmjs.org/mailparser
15 verbose request no auth needed
16 info attempt registry request try #1 at 8:58:37 AM
17 verbose request id 8866e17be0896c65
18 verbose etag "3LQEBG0GG9PV1LMI8XB3KRV8B"
19 http request GET https://registry.npmjs.org/mailparser
20 http 304 https://registry.npmjs.org/mailparser
21 verbose headers { date: 'Tue, 23 Aug 2016 07:58:37 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"3LQEBG0GG9PV1LMI8XB3KRV8B"',
21 verbose headers   age: '243',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lhr6328-LHR',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1471939117.902335,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Tue, 23 Aug 2016 07:58:37 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"3LQEBG0GG9PV1LMI8XB3KRV8B"',
22 silly get     age: '243',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lhr6328-LHR',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1471939117.902335,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/mailparser from cache
24 verbose get saving mailparser to /Users/darren/.npm/registry.npmjs.org/mailparser/.cache.json
25 verbose correctMkdir /Users/darren/.npm correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install mailparser as a dependency of itself
43 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/darren/dev/mailReader
45 error Darwin 15.5.0
46 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mailparser" "--save"
47 error node v6.2.1
48 error npm  v3.9.3
49 error code ENOSELF
50 error Refusing to install mailparser as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by andris9** [comment]
How do you try to install it? This is what I see when installing from command line:

```
$ npm install mailparser
/Users/andris/Desktop
└─┬ mailparser@0.6.1
  ├─┬ encoding@0.1.12
  │ └── iconv-lite@0.4.13
  ├── mime@1.3.4
  ├─┬ mimelib@0.2.19
  │ └── addressparser@0.3.2
  └─┬ uue@3.0.0
    └── extend@3.0.0
```

**Comment by darren-white72** [comment]
I use the following 
`npm install mailparser --save `

**Comment by andris9** [comment]
Are your running this command from the mailparser folder? This is when you should see the error you have

**Comment by darren-white72** [comment]
I think I have found the issue. 
The project folder I'm using is called mailReader, when I run the command to install your module within this folder I get the error.
I have just tried to install your module in a folder called testing and it worked with no issues.

Looks like you can't install the module if the parent folder contains the work mail.

Thank you for you quick response.
