### ISSUE TITLE
content garbled when parse an email with Chinese characters,Content-Transfer-Encoding: 8bit,charset="gbk"

### ISSUE THREAD

**Issue by Yonysun** [andris9/mailparser#161]
There is an email with Chinese characters, when I use mailparser to  parse the mail ,it's content was garbled.

in the mailhead

> Content-Type: text/plain; charset="gbk"; format=flowed
> Content-Transfer-Encoding: 8bit

this is the mail source code:

```
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101
 Thunderbird/45.2.0
Content-Type: text/plain; charset="gbk"; format=flowed
Content-Transfer-Encoding: 8bit
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 06
MIME-Version: 1.0

sdfafµØ·½Èö·¢¸åÊ±´ó¹ø·¹ÉÏµÛ¸ø

```
before convert to 'utf-8' charset, the content is 
`sdfafÂµÃÂ·Â½ÃÃ¶Â·Â¢Â¸Ã¥ÃÂ±Â´Ã³Â¹Ã¸Â·Â¹ÃÃÂµÃÂ¸Ã¸` 
that the mailparser read out

please tell me how to get the correct content?

**Comment by andris9** [comment]
How did you get the file, did you copy and paste it or did you open the eml file with an editor before you parsed it with Mailparser? Mailparser should be able to handle gbk charset but if you touch that file with an editor, it probably breaks the original characters and converts these to something else

**Comment by Yonysun** [comment]
I retrieved the mail withthe pop3 protocol and then saved it to local database,before the save step, I convert the mail buffer to string,using the follow code:
```
client.retrieve(i,function (err2,fullMail) {
                // console.log(err2,fullMail);
                if(!err2){
                    if(fullMail){
                         var mailSrc = fullMail.toString('binary');
                         // execute the step of saving mail
                         // ...
                    }
                }
});
```

this is the parse code:
```
    var MailParser = require("mailparser").MailParser;
    var mailparser = new MailParser({
        streamAttachments: true
    });
    mailparser.on("end", function(mail_object){
        // console.log("mailObject:", mail_object);
        _callback(mail_object);
    });
    mailparser.write(mailSrc);
    mailparser.end();
```
before the write step,the mailSrc from the console log is this:

```
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101
 Thunderbird/45.2.0
Content-Type: text/plain; charset="gbk"; format=flowed
Content-Transfer-Encoding: 8bit
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 06
MIME-Version: 1.0

sdfafµØ·½Èö·¢¸åÊ±´ó¹ø·¹ÉÏµÛ¸ø

```

I copied the last line 
`sdfafµØ·½Èö·¢¸åÊ±´ó¹ø·¹ÉÏµÛ¸ø`

then decode it with the 'iconv-lite' module, and the result is correct:
`sdfaf地方撒发稿时大锅饭上帝给`

but the mailparser result is:
`sdfaf碌脴路陆脠枚路垄赂氓脢卤麓贸鹿酶路鹿脡脧碌脹赂酶`

I debuged the mailparser.js and found

**Comment by Yonysun** [comment]
thank you andris9.

the issue is solved already. 

I converted the mail source to base64 charset before saving to local database,and it works correctly
